/* GENERATED BY scripts/images.mjs — DO NOT EDIT.
 *
 * Run `npm run images` after adding or replacing anything in assets/photos/.
 *
 * The keys below are the only photographs that exist. Because PackageImage.key is
 * typed as ImageKey, referring to one that has not been processed fails
 * `npm run typecheck` instead of shipping a broken <img> — which is the failure
 * this whole pipeline exists to make impossible.
 */

export interface GeneratedImage {
  /** Intrinsic size of the largest variant, so layout can be reserved up front. */
  readonly width: number;
  readonly height: number;
  /** Ready-made srcset entries, widest-capable format first. */
  readonly avif: readonly string[];
  readonly webp: readonly string[];
  /** Plain JPEG for the <img> inside <picture>. */
  readonly fallback: string;
}

export const IMAGES = {

} as const satisfies Record<string, GeneratedImage>;

/** Every processed photograph. Empty until assets/photos/ has something in it. */
export type ImageKey = keyof typeof IMAGES;
