/* GENERATED BY scripts/images.mjs — DO NOT EDIT.
 *
 * Run `npm run images` after adding or replacing anything in assets/photos/.
 *
 * The keys below are the only photographs that exist. Because PackageImage.key is
 * typed as ImageKey, referring to one that has not been processed fails
 * `npm run typecheck` instead of shipping a broken <img> — which is the failure
 * this whole pipeline exists to make impossible.
 */

export interface GeneratedImage {
  /** Intrinsic size of the largest variant, so layout can be reserved up front. */
  readonly width: number;
  readonly height: number;
  /** Ready-made srcset entries, widest-capable format first. */
  readonly avif: readonly string[];
  readonly webp: readonly string[];
  /** Plain JPEG for the <img> inside <picture>. */
  readonly fallback: string;
}

export const IMAGES = {
  'airline-ba': {
    width: 800,
    height: 324,
    avif: [
      '/img/airline-ba-400.avif 400w',
      '/img/airline-ba-800.avif 800w',
    ],
    webp: [
      '/img/airline-ba-400.webp 400w',
      '/img/airline-ba-800.webp 800w',
    ],
    fallback: '/img/airline-ba-800.jpg',
  },
  'airline-ek': {
    width: 800,
    height: 800,
    avif: [
      '/img/airline-ek-400.avif 400w',
      '/img/airline-ek-800.avif 800w',
    ],
    webp: [
      '/img/airline-ek-400.webp 400w',
      '/img/airline-ek-800.webp 800w',
    ],
    fallback: '/img/airline-ek-800.jpg',
  },
  'airline-ey': {
    width: 800,
    height: 284,
    avif: [
      '/img/airline-ey-400.avif 400w',
      '/img/airline-ey-800.avif 800w',
    ],
    webp: [
      '/img/airline-ey-400.webp 400w',
      '/img/airline-ey-800.webp 800w',
    ],
    fallback: '/img/airline-ey-800.jpg',
  },
  'airline-gf': {
    width: 800,
    height: 290,
    avif: [
      '/img/airline-gf-400.avif 400w',
      '/img/airline-gf-800.avif 800w',
    ],
    webp: [
      '/img/airline-gf-400.webp 400w',
      '/img/airline-gf-800.webp 800w',
    ],
    fallback: '/img/airline-gf-800.jpg',
  },
  'airline-qr': {
    width: 800,
    height: 226,
    avif: [
      '/img/airline-qr-400.avif 400w',
      '/img/airline-qr-800.avif 800w',
    ],
    webp: [
      '/img/airline-qr-400.webp 400w',
      '/img/airline-qr-800.webp 800w',
    ],
    fallback: '/img/airline-qr-800.jpg',
  },
  'airline-sv': {
    width: 800,
    height: 800,
    avif: [
      '/img/airline-sv-400.avif 400w',
      '/img/airline-sv-800.avif 800w',
    ],
    webp: [
      '/img/airline-sv-400.webp 400w',
      '/img/airline-sv-800.webp 800w',
    ],
    fallback: '/img/airline-sv-800.jpg',
  },
  'flight-approach': {
    width: 1600,
    height: 711,
    avif: [
      '/img/flight-approach-400.avif 400w',
      '/img/flight-approach-800.avif 800w',
      '/img/flight-approach-1200.avif 1200w',
      '/img/flight-approach-1600.avif 1600w',
    ],
    webp: [
      '/img/flight-approach-400.webp 400w',
      '/img/flight-approach-800.webp 800w',
      '/img/flight-approach-1200.webp 1200w',
      '/img/flight-approach-1600.webp 1600w',
    ],
    fallback: '/img/flight-approach-800.jpg',
  },
  'haram-courtyard': {
    width: 1600,
    height: 1200,
    avif: [
      '/img/haram-courtyard-400.avif 400w',
      '/img/haram-courtyard-800.avif 800w',
      '/img/haram-courtyard-1200.avif 1200w',
      '/img/haram-courtyard-1600.avif 1600w',
    ],
    webp: [
      '/img/haram-courtyard-400.webp 400w',
      '/img/haram-courtyard-800.webp 800w',
      '/img/haram-courtyard-1200.webp 1200w',
      '/img/haram-courtyard-1600.webp 1600w',
    ],
    fallback: '/img/haram-courtyard-800.jpg',
  },
  'haram-night': {
    width: 1600,
    height: 1280,
    avif: [
      '/img/haram-night-400.avif 400w',
      '/img/haram-night-800.avif 800w',
      '/img/haram-night-1200.avif 1200w',
      '/img/haram-night-1600.avif 1600w',
    ],
    webp: [
      '/img/haram-night-400.webp 400w',
      '/img/haram-night-800.webp 800w',
      '/img/haram-night-1200.webp 1200w',
      '/img/haram-night-1600.webp 1600w',
    ],
    fallback: '/img/haram-night-800.jpg',
  },
  'kaaba-day': {
    width: 1600,
    height: 2133,
    avif: [
      '/img/kaaba-day-400.avif 400w',
      '/img/kaaba-day-800.avif 800w',
      '/img/kaaba-day-1200.avif 1200w',
      '/img/kaaba-day-1600.avif 1600w',
    ],
    webp: [
      '/img/kaaba-day-400.webp 400w',
      '/img/kaaba-day-800.webp 800w',
      '/img/kaaba-day-1200.webp 1200w',
      '/img/kaaba-day-1600.webp 1600w',
    ],
    fallback: '/img/kaaba-day-800.jpg',
  },
  'kiswah-detail': {
    width: 1600,
    height: 2845,
    avif: [
      '/img/kiswah-detail-400.avif 400w',
      '/img/kiswah-detail-800.avif 800w',
      '/img/kiswah-detail-1200.avif 1200w',
      '/img/kiswah-detail-1600.avif 1600w',
    ],
    webp: [
      '/img/kiswah-detail-400.webp 400w',
      '/img/kiswah-detail-800.webp 800w',
      '/img/kiswah-detail-1200.webp 1200w',
      '/img/kiswah-detail-1600.webp 1600w',
    ],
    fallback: '/img/kiswah-detail-800.jpg',
  },
  'makkah-skyline-night': {
    width: 1600,
    height: 1200,
    avif: [
      '/img/makkah-skyline-night-400.avif 400w',
      '/img/makkah-skyline-night-800.avif 800w',
      '/img/makkah-skyline-night-1200.avif 1200w',
      '/img/makkah-skyline-night-1600.avif 1600w',
    ],
    webp: [
      '/img/makkah-skyline-night-400.webp 400w',
      '/img/makkah-skyline-night-800.webp 800w',
      '/img/makkah-skyline-night-1200.webp 1200w',
      '/img/makkah-skyline-night-1600.webp 1600w',
    ],
    fallback: '/img/makkah-skyline-night-800.jpg',
  },
  'nabawi-green-dome': {
    width: 1600,
    height: 2842,
    avif: [
      '/img/nabawi-green-dome-400.avif 400w',
      '/img/nabawi-green-dome-800.avif 800w',
      '/img/nabawi-green-dome-1200.avif 1200w',
      '/img/nabawi-green-dome-1600.avif 1600w',
    ],
    webp: [
      '/img/nabawi-green-dome-400.webp 400w',
      '/img/nabawi-green-dome-800.webp 800w',
      '/img/nabawi-green-dome-1200.webp 1200w',
      '/img/nabawi-green-dome-1600.webp 1600w',
    ],
    fallback: '/img/nabawi-green-dome-800.jpg',
  },
  'nabawi-twilight': {
    width: 1600,
    height: 1067,
    avif: [
      '/img/nabawi-twilight-400.avif 400w',
      '/img/nabawi-twilight-800.avif 800w',
      '/img/nabawi-twilight-1200.avif 1200w',
      '/img/nabawi-twilight-1600.avif 1600w',
    ],
    webp: [
      '/img/nabawi-twilight-400.webp 400w',
      '/img/nabawi-twilight-800.webp 800w',
      '/img/nabawi-twilight-1200.webp 1200w',
      '/img/nabawi-twilight-1600.webp 1600w',
    ],
    fallback: '/img/nabawi-twilight-800.jpg',
  },
  'pilgrims-ihram': {
    width: 1600,
    height: 1586,
    avif: [
      '/img/pilgrims-ihram-400.avif 400w',
      '/img/pilgrims-ihram-800.avif 800w',
      '/img/pilgrims-ihram-1200.avif 1200w',
      '/img/pilgrims-ihram-1600.avif 1600w',
    ],
    webp: [
      '/img/pilgrims-ihram-400.webp 400w',
      '/img/pilgrims-ihram-800.webp 800w',
      '/img/pilgrims-ihram-1200.webp 1200w',
      '/img/pilgrims-ihram-1600.webp 1600w',
    ],
    fallback: '/img/pilgrims-ihram-800.jpg',
  },
  'tawaf-crowd': {
    width: 1600,
    height: 2133,
    avif: [
      '/img/tawaf-crowd-400.avif 400w',
      '/img/tawaf-crowd-800.avif 800w',
      '/img/tawaf-crowd-1200.avif 1200w',
      '/img/tawaf-crowd-1600.avif 1600w',
    ],
    webp: [
      '/img/tawaf-crowd-400.webp 400w',
      '/img/tawaf-crowd-800.webp 800w',
      '/img/tawaf-crowd-1200.webp 1200w',
      '/img/tawaf-crowd-1600.webp 1600w',
    ],
    fallback: '/img/tawaf-crowd-800.jpg',
  },
} as const satisfies Record<string, GeneratedImage>;

/** Every processed photograph. Empty until assets/photos/ has something in it. */
export type ImageKey = keyof typeof IMAGES;
